# docker-compose.yml

services:
  # --- API Gateway ---
  gateway:
    image: traefik:v2.11 
    container_name: traefik_gateway

    ports:
      - "80:80"       # Map host port 80 to Traefik's web entrypoint
      - "8080:8080"   # Map host port 8080 to Traefik's dashboard entrypoint (container port 8181)
  
    volumes:
      # Mount Docker socket to allow Traefik to detect containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount static config file (relative path from docker-compose.yml location)
      - ./gateway/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - webnet
    labels:
      # Explicitly create a router for the dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=dashboard" # Use the dashboard entrypoint
      # Specify the Docker network Traefik should use for this service
      - "traefik.docker.network=webnet"

  # --- Backend Services ---
  series-api:
    build:
      context: ./services/series-api
    container_name: series_api
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
      # Router definition: Listen for path starting with /api/series
      - "traefik.http.routers.series-api.rule=PathPrefix(`/api/series`)"
      - "traefik.http.routers.series-api.priority=10"
      - "traefik.http.routers.series-api.entrypoints=web"
      # Service definition: Forward matching requests to this container on port 8081
      - "traefik.http.services.series-api.loadbalancer.server.port=8081"
      # Specify the Docker network Traefik should use for this service
      - "traefik.docker.network=webnet"

  anime-api:
    build:
      context: ./services/anime-api
    container_name: anime_api
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
      # Router definition: Listen for path starting with /api/anime
      - "traefik.http.routers.anime-api.rule=PathPrefix(`/api/anime`)"
      - "traefik.http.routers.anime-api.entrypoints=web"
      - "traefik.http.services.anime-api.loadbalancer.server.port=8082"
      - "traefik.docker.network=webnet"

  movies-api:
    build:
      context: ./services/movies-api
    container_name: movies_api
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
      # Router definition: Listen for path starting with /api/movies
      - "traefik.http.routers.movies-api.rule=PathPrefix(`/api/movies`)"
      - "traefik.http.routers.movies-api.entrypoints=web"
      - "traefik.http.services.movies-api.loadbalancer.server.port=8083"
      - "traefik.docker.network=webnet"

  # --- Frontend Service ---
  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    networks:
      - webnet
    depends_on: # Optional: wait for APIs (doesn't guarantee they are *ready*, just started)
      - series-api
      - anime-api
      - movies-api
    labels:
      - "traefik.enable=true"
      # Router definition: Catches remaining requests to Host(`localhost`)
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.entrypoints=web"
      # Service definition: Forward to the Next.js server running in the container on port 3000
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=webnet"

# --- Network Configuration ---
networks:
  webnet:
    driver: bridge # Default network driver 